export default {
  MOVIES: 'MOVIES',
  CURRENT_PAGE: 'CURRENT_PAGE',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  TOGGLE_SEARCH: 'TOGGLE_SEARCH',
  TOGGLE_SEARCH_NO_DATA: 'TOGGLE_SEARCH_NO_DATA',
  SHOW_NOTIFY: 'SHOW_NOTIFY'
}